/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx,js,jsx}',
    './components/**/*.{ts,tsx,js,jsx}',
    './lib/**/*.{ts,tsx,js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        // ── Material Design 3 color tokens ──────────────────────────────
        'primary':                  '#adc6ff',
        'on-primary':               '#002e6a',
        'primary-container':        '#4d8eff',
        'on-primary-container':     '#00285d',
        'primary-fixed':            '#d8e2ff',
        'primary-fixed-dim':        '#adc6ff',
        'on-primary-fixed':         '#001a42',
        'on-primary-fixed-variant': '#004395',
        'secondary':                '#4edea3',
        'on-secondary':             '#003824',
        'secondary-container':      '#00a572',
        'on-secondary-container':   '#00311f',
        'secondary-fixed':          '#6ffbbe',
        'secondary-fixed-dim':      '#4edea3',
        'on-secondary-fixed':       '#002113',
        'on-secondary-fixed-variant':'#005236',
        'tertiary':                 '#ffb786',
        'on-tertiary':              '#502400',
        'tertiary-container':       '#df7412',
        'on-tertiary-container':    '#461f00',
        'tertiary-fixed':           '#ffdcc6',
        'tertiary-fixed-dim':       '#ffb786',
        'on-tertiary-fixed':        '#311400',
        'on-tertiary-fixed-variant':'#723600',
        'error':                    '#ffb4ab',
        'on-error':                 '#690005',
        'error-container':          '#93000a',
        'on-error-container':       '#ffdad6',
        'background':               '#10131a',
        'on-background':            '#e1e2ec',
        'surface':                  '#10131a',
        'on-surface':               '#e1e2ec',
        'surface-variant':          '#32353c',
        'on-surface-variant':       '#c2c6d6',
        'surface-container-lowest': '#0b0e15',
        'surface-container-low':    '#191b23',
        'surface-container':        '#1d2027',
        'surface-container-high':   '#272a31',
        'surface-container-highest':'#32353c',
        'surface-bright':           '#363941',
        'surface-dim':              '#10131a',
        'surface-tint':             '#adc6ff',
        'outline':                  '#8c909f',
        'outline-variant':          '#424754',
        'inverse-surface':          '#e1e2ec',
        'inverse-on-surface':       '#2e3038',
        'inverse-primary':          '#005ac2',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      spacing: {
        'margin-desktop':  '32px',
        'margin-mobile':   '16px',
        'container-max':   '1440px',
        'gutter':          '16px',
        'unit':            '4px',
      },
      fontFamily: {
        sans:         ['Inter', 'sans-serif'],
        mono:         ['JetBrains Mono', 'monospace'],
        'body-lg':    ['Inter', 'sans-serif'],
        'body-sm':    ['Inter', 'sans-serif'],
        'headline-lg':['Inter', 'sans-serif'],
        'headline-md':['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'data-mono':  ['JetBrains Mono', 'monospace'],
        display:      ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg':     ['16px', { lineHeight: '1.6',  fontWeight: '400' }],
        'body-sm':     ['14px', { lineHeight: '1.5',  fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '1.3',  letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '1.4',  fontWeight: '600' }],
        'label-caps':  ['11px', { lineHeight: '1',    letterSpacing: '0.05em', fontWeight: '600' }],
        'data-mono':   ['13px', { lineHeight: '1.4',  fontWeight: '400' }],
        display:       ['36px', { lineHeight: '1.2',  letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
